import type { Product } from "~/types";

export const products: Product[] = [
  {
    id: 1,
    imageUrl: "https://picsum.photos/370/316",
    name: "Fahrrad",
    price: 100,
    distance: 0.7,
    tags: [
      "sport",
      "outdoor",
      "fahrrad",
      "bike",
      "rad",
      "velo",
      "mountainbike",
    ],
  },
  {
    id: 2,
    imageUrl: "https://picsum.photos/370/316",
    name: "Schuhe",
    price: 50,
    distance: 0.5,
    tags: ["sport", "outdoor", "schuhe", "shoes", "sneaker", "sneakers"],
  },
  {
    id: 12345,
    imageUrl: "https://picsum.photos/370/316",
    name: "Radon ZR Team 8.0",
    price: 1299.99,
    distance: 3.2,
    tags: ["Sport", "Mountainbike", "Fahrrad"],
  },
  {
    id: 23456,
    imageUrl: "https://picsum.photos/370/316",
    name: "Cannondale Habit 6",
    price: 1899.99,
    distance: 1.7,
    tags: ["Sport", "Mountainbike", "Fahrrad"],
  },
  {
    id: 34567,
    imageUrl: "https://picsum.photos/370/316",
    name: "Specialized Sirrus X 4.0",
    price: 949.99,
    distance: 0.8,
    tags: ["Sport", "Outdoor", "Fahrrad"],
  },
  {
    id: 45678,
    imageUrl: "https://picsum.photos/370/316",
    name: "Bulls Copperhead 3",
    price: 899.99,
    distance: 2.1,
    tags: ["Sport", "Mountainbike", "Fahrrad"],
  },
  {
    id: 56789,
    imageUrl: "https://picsum.photos/370/316",
    name: "Cube Nature Pro",
    price: 799.99,
    distance: 0.6,
    tags: ["Fahrrad", "Trekkingrad", "Outdoor"],
  },
  {
    id: 67890,
    imageUrl: "https://picsum.photos/370/316",
    name: "Trek Verve+ 2",
    price: 2299.99,
    distance: 1.3,
    tags: ["Fahrrad", "E-Bike", "Trekkingrad"],
  },
  {
    id: 78901,
    imageUrl: "https://picsum.photos/370/316",
    name: "Giant Trance 29 3",
    price: 1699.99,
    distance: 4.2,
    tags: ["Sport", "Mountainbike", "Fahrrad"],
  },
  {
    id: 89012,
    imageUrl: "https://picsum.photos/370/316",
    name: "Orbea Gain F30",
    price: 2899.99,
    distance: 0.9,
    tags: ["Fahrrad", "E-Bike", "Outdoor"],
  },
  {
    id: 90123,
    imageUrl: "https://picsum.photos/370/316",
    name: "Scott Sub Active eRide",
    price: 2599.99,
    distance: 1.5,
    tags: ["Fahrrad", "E-Bike", "Citybike"],
  },
  {
    id: 10111,
    imageUrl: "https://picsum.photos/370/316",
    name: "Raleigh Centros Tour Low Step",
    price: 2199.99,
    distance: 1.8,
    tags: ["Fahrrad", "E-Bike", "Citybike"],
  },
  {
    id: 8,
    imageUrl: "https://picsum.photos/370/316",
    name: "Adidas Ultraboost 21",
    price: 149.99,
    distance: 0.5,
    tags: ["shoes", "running", "sport", "adidas", "ultraboost", "sneakers"],
  },
  {
    id: 9,
    imageUrl: "https://picsum.photos/370/316",
    name: "Levi's 501 Original Fit Jeans",
    price: 79.99,
    distance: 0.1,
    tags: ["jeans", "clothing", "fashion", "levis", "denim", "pants"],
  },
  {
    id: 10,
    imageUrl: "https://picsum.photos/370/316",
    name: "Apple iPad Pro 12.9-inch",
    price: 999.0,
    distance: 0.3,
    tags: ["ipad", "tablet", "apple", "electronics", "gadgets", "mobile"],
  },
  {
    id: 11,
    imageUrl: "https://picsum.photos/370/316",
    name: "Samsung Galaxy S21 Ultra",
    price: 1199.0,
    distance: 0.8,
    tags: ["phone", "samsung", "galaxy", "electronics", "smartphone", "mobile"],
  },
  {
    id: 12,
    imageUrl: "https://picsum.photos/370/316",
    name: "Ikea Billy Bookcase",
    price: 99.0,
    distance: 0.4,
    tags: ["furniture", "home", "ikea", "bookcase", "shelf", "storage"],
  },
  {
    id: 13,
    imageUrl: "https://picsum.photos/370/316",
    name: "Dyson V11 Absolute Pro",
    price: 699.0,
    distance: 0.2,
    tags: ["vacuum", "cleaner", "home", "dyson", "electronics", "gadgets"],
  },
  {
    id: "dd3079c3-3b0f-4372-a156-0e04c2d92811",
    imageUrl: "https://picsum.photos/370/316",
    name: "Bosch WAW28570 Waschmaschine",
    price: 749.99,
    distance: 0.7,
    tags: ["waschmaschine", "haushalt", "elektronik", "geräte", "bosch"],
  },
  {
    id: "8f464f5e-0a2b-4f1f-b0fc-5d89e3f3d3e6",
    imageUrl: "https://picsum.photos/370/316",
    name: "Philips HD9741/10 Airfryer",
    price: 179.99,
    distance: 0.4,
    tags: ["airfryer", "fritteuse", "küche", "elektronik", "geräte", "philips"],
  },
  {
    id: "a7b1c063-8b8a-4660-975a-53c60d2280b7",
    imageUrl: "https://picsum.photos/370/316",
    name: "Tefal OptiGrill Elite",
    price: 249.99,
    distance: 0.3,
    tags: ["grill", "küche", "elektronik", "geräte", "tefal"],
  },
  {
    id: "ab0b69c9-9c1b-4a57-b6a3-7ca736b2d2b8",
    imageUrl: "https://picsum.photos/370/316",
    name: "Bosch Home and Garden PSB 1800 LI-2",
    price: 99.99,
    distance: 0.6,
    tags: [
      "akkuschrauber",
      "werkzeug",
      "haushalt",
      "elektronik",
      "geräte",
      "bosch",
    ],
  },
  {
    id: "36a45a1c-4e58-4e84-8c56-dca9a10c9d4a",
    imageUrl: "https://picsum.photos/370/316",
    name: "Ikea Strandmon Sessel",
    price: 249.0,
    distance: 0.1,
    tags: ["sessel", "wohnzimmer", "möbel", "ikea"],
  },
  {
    id: "222b06e9-32d9-44d4-a774-cd6a017a60c7",
    imageUrl: "https://picsum.photos/370/316",
    name: "Kärcher K 5 Premium Full Control Plus",
    price: 349.0,
    distance: 0.9,
    tags: ["hochdruckreiniger", "garten", "werkzeug", "geräte", "kärcher"],
  },
  {
    id: "7ee79d21-2070-48e1-9075-f7de52e5fb5d",
    imageUrl: "https://picsum.photos/370/316",
    name: "Sony PlayStation 5",
    price: 499,
    distance: 0.3,
    tags: [
      "Gaming",
      "Konsolen",
      "Spiele",
      "Playstation",
      "Sony",
      "Unterhaltung",
      "Technologie",
      "Elektronik",
    ],
  },
  {
    id: "9b6f050c-4f31-4fb8-8f4f-4a6ce797df6f",
    imageUrl: "https://picsum.photos/370/316",
    name: "Samsung Galaxy S21",
    price: 799,
    distance: 0.2,
    tags: [
      "Smartphone",
      "Android",
      "Samsung",
      "Technologie",
      "Elektronik",
      "Mobilfunk",
      "Handy",
      "Telefon",
    ],
  },
  {
    id: "ecf4a8f1-c9d9-4a98-b37f-b0f890c0c7e5",
    imageUrl: "https://picsum.photos/370/316",
    name: "Bosch Waschmaschine",
    price: 899,
    distance: 1.5,
    tags: [
      "Haushaltsgeräte",
      "Waschmaschine",
      "Bosch",
      "Wäsche",
      "Reinigung",
      "Haushalt",
      "Wohnen",
    ],
  },
  {
    id: "c87f7a3a-eeb3-4692-a18f-7a9f5e774d8c",
    imageUrl: "https://picsum.photos/370/316",
    name: "Apple iPad Pro",
    price: 899,
    distance: 0.4,
    tags: [
      "Tablet",
      "Apple",
      "iOS",
      "iPad",
      "Technologie",
      "Elektronik",
      "Unterhaltung",
    ],
  },
  {
    id: "4c4dd4cb-4d70-4f77-8f15-7b101299ed6f",
    imageUrl: "https://picsum.photos/370/316",
    name: "Bose QuietComfort 35 II",
    price: 299,
    distance: 0.1,
    tags: [
      "Kopfhörer",
      "Audio",
      "Bose",
      "Noise-Cancelling",
      "Musik",
      "Unterhaltung",
      "Technologie",
      "Elektronik",
    ],
  },
  {
    id: "6419a7c5-5d28-45c3-8d2e-c0f1d133decc",
    imageUrl: "https://picsum.photos/370/316",
    name: "Ralph Lauren Polo-Shirt",
    price: 89,
    distance: 0.2,
    tags: [
      "Kleidung",
      "Mode",
      "Polo-Shirt",
      "Ralph Lauren",
      "Herrenmode",
      "Freizeit",
      "Stil",
      "Fashion",
    ],
  },
];
